version: '2'
# service
services:

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana-6.6.0
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_HOSTS: http://elasticsearch
      VIRTUAL_HOST: kibana.local
    restart: always
    links:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  default:
    external:
      name: common_link
